name: thanatos
description: OSTree layer on top of ublue-silverblue-main

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - from-file: commons/100-base.yml
  - from-file: gnome/102-gnome-special.yml
  - type: signing
