name: thanatos
description: OSTree layer on top of ublue-silverblue-main

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - from-file: commons/100-base.yml
  - from-file: rpm-ostree/101-rpm-os-tree.yml
  - from-file: rpm-ostree/102-rpm-os-tree-gnome.yml
  - from-file: scripts/103-scripts.yml
  - from-file: scripts/104-scripts-mutter-patched.yml
