name: thanatos
description: OSTree layer on top of ublue-silverblue-main

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
    install:
      - neofetch
      - podman-docker
      - fprintd
      - xorg-x11-server-Xwayland
      - btop
      - unrar
      - unzip
      - p7zip
      - file-roller
      # Tuned to replace power-profiles-daemon
      - tuned
      - tuned-ppd
      - tuned-utils
      - tuned-gtk
      - tuned-profiles-atomic
      - tuned-profiles-cpu-partitioning
      # From COPR
      - system76-scheduler
    remove:
      - firefox
      - firefox-langpacks
      - fedora-bookmarks
      - power-profiles-daemon
      - htop
      # Removing gnome applications
      - gnome-tour
      - gnome-system-monitor

  - type: yafti

  - type: akmods
    install:
      - v4l2loopback

  - type: bling
    install:
      - gnome-mutter-patched
      - dconf-update-service

  - type: systemd
    system:
      enabled:
        - tuned.service
        - com.system76.Scheduler.service

  - type: signing
