name: thanatos
description: OSTree layer on top of ublue-silverblue-main

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - podman-docker
      - fprintd
      - xorg-x11-server-Xwayland
      - btop
      - unrar
      - unzip
      - p7zip
      - file-roller
      # Tuned to replace power-profiles-daemon
      - tuned
      - tuned-ppd
      - tuned-utils
      - tuned-gtk
      - tuned-profiles-atomic
      - tuned-profiles-cpu-partitioning
    remove:
      - firefox
      - firefox-langpacks
      - fedora-bookmarks
      - power-profiles-daemon

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - io.github.realmazharhussain.GdmSettings
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
        - it.mijorus.gearlever
        - io.github.dvlv.boxbuddyrs
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.font-viewer
        - com.github.wwmm.easyeffects
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      remove:
        - org.gnome.eog

  - type: akmods
    install:
      - v4l2loopback

  - type: bling
    install:
      - gnome-mutter-patched
      - system76-scheduler
      - dconf-update-service

  - type: systemd
    system:
      enabled:
        - tuned.service
        - com.system76.Scheduler.service

  - type: signing
