name: thanatos
description: OSTree layer on top of ublue-silverblue-main

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: common_modules/xdg-autostart-workaround.yml
  - from-file: common_modules/files.yml
  - from-file: common_modules/rpm-ostree.yml
  - from-file: common_modules/rpm-ostree-gnome.yml
  - from-file: common_modules/default-flatpaks.yml
  - from-file: common_modules/scripts.yml
  - from-file: common_modules/bling.yml
  - from-file: common_modules/systemd.yml
  - from-file: common_modules/signing.yml
