type: rpm-ostree
install:
  - gvfs
  - gvfs-afc
  - gvfs-afp
  - gvfs-fuse
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-archive
  - gnome-console
  - gnome-shell-extension-pop-shell
  - gnome-shell-extension-system76-scheduler
  - gnome-shell-extension-appindicator
remove:
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-shell-extension-background-logo
  - gnome-classic-session-xsession
  - gnome-classic-session
